environmentvariabledefinition:
  '@schemaname': xrplhack_GithubXrplHack
  defaultvalue: Text to review
  displayname:
    '@default': GithubXrplHack
    label:
      '@description': GithubXrplHack
      '@languagecode': 1033
  introducedversion: 1.0.0.4
  iscustomizable: 1
  isrequired: 0
  secretstore: 0
  type: 100000000
